apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  template:
    spec:
      volumes:
      - name: user-files
        gitRepo:
          repository: https://github.com/sellerin/gatling-cluster.git
          revision: master