apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: batch-watcher-role
  namespace: dev
rules:
- apiGroups: [""]
  verbs: ["get", "list"]
  resources: ["services"]
- apiGroups: ["batch", "extensions","apps" ]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: batch-watcher-rb
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: batch-watcher-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: dev