kind: Service
apiVersion: v1
metadata:
  name: static-web
  namespace: dev
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
  selector:
    role: static-web
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: static-web
  namespace: dev
spec:
  replicas: 1
  selector:
    role: static-web
  template:
    metadata:
      labels:
        role: static-web
    spec:
      containers:
      - name: static-web
        image: nginx
        ports:
          - name: http
            containerPort: 80
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nfs
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs
