apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  completions: 2
  parallelism: 2
  activeDeadlineSeconds: 400
  template:
    spec:
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
      containers:
      - name: main
        image: eu.gcr.io/iron-inkwell-205415/perf:1.0.0-SNAPSHOT
        volumeMounts:
            - name: nfs
              mountPath: /gatling-charts-highcharts-bundle-3.0.2/results
      restartPolicy: Never
  backoffLimit: 1
