apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  template:
    spec:
      containers:
      - name: main
        env:
        - name: SIMULATION_NAME
          value: "c2gwebaws.C2gwebSimulation"